# Generated by Django 5.2 on 2025-04-13 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(default='COMPRAS', max_length=100)),
                ('fecha', models.DateField()),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('moneda', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('serie', models.CharField(blank=True, max_length=10, null=True)),
                ('correlativo', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo_documento_adicional', models.CharField(blank=True, max_length=50, null=True)),
                ('serie_adicional', models.CharField(blank=True, max_length=10, null=True)),
                ('correlativo_adicional', models.CharField(blank=True, max_length=10, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucursales.almacen')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucursales.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('igv', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.producto')),
            ],
        ),
    ]
