# Generated by Django 5.2 on 2025-04-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('BIEN', 'Bien'), ('SERVICIO', 'Servicio')], max_length=10)),
                ('unidad', models.CharField(max_length=20)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(default='Activo', max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
